Repository cloudposse/docs, pull requests merged in 2018-05, with the labels that each got.

#35 Added documentations for prometheus
  content/kubernetes-backing-services/monitoring/prometheus-alerts-grafana.md
  content/monitoring-and-alerting/prometheus/_index.md
  content/monitoring-and-alerting/prometheus/prometheus-operator.md
  static/assets/324asd-Prometheus_architecture.png
Labels: documentation

#70 Document why terraform apply fails
  content/faq/error-applying-terraform-plan.md
Labels: documentation

#69 Kube lego privacy error
  content/faq/kube-lego-privacy-error.md
  static/assets/kube-lego-privacy-error-9d1bee77.png
Labels: documentation

#68 Add ability to include from github
  content/terraform-modules/root/_index.md
  content/terraform-modules/root/codefresh-pipeline.md
  layouts/shortcodes/include-github.html
Labels: enhancement

#73 Document Secrets Management
  Makefile
  content/geodesic/s3fs.md
  content/glossary/dev-shm.md
  content/glossary/geodesic-module.md
  content/glossary/geodesic-shell.md
  content/glossary/hcl.md
  content/glossary/mfa.md
  content/glossary/sso.md
  content/learn-by-example/_index.md
  content/secrets-management/_index.md
  content/secrets-management/anti-patterns.md
  content/secrets-management/aws-kms.md
  content/secrets-management/aws.md
  content/secrets-management/best-practices.md
  content/secrets-management/development.md
  content/secrets-management/kubernetes.md
  content/secrets-management/terraform.md
  content/tools/chamber.md
Labels: documentation

#72 Document Cluster Creation
  .config.cson
  .snippets/hugo/docs.misc.snippet.cson
  content/geodesic/module/usage/_index.md
  content/geodesic/module/usage/examples/Dockerfile
  content/geodesic/module/usage/examples/assume-role.txt
  content/geodesic/module/usage/examples/exit-geodesic-shell.txt
  content/geodesic/module/usage/examples/kops-update-cluster-initial.txt
  content/geodesic/module/usage/examples/terraform-apply-tfstate-backend.txt
  content/geodesic/module/usage/examples/tfstate-backend.tf
  content/geodesic/module/usage/with-kops.md
  content/geodesic/module/usage/with-terraform.md
  content/kubernetes-backing-services/_index.md
  content/kubernetes-backing-services/external-dns/external-dns.md
  content/kubernetes-backing-services/ingress/examples/nginx-ingess-helmfile.yaml
  content/kubernetes-backing-services/ingress/examples/nginx-ingress-usage-helm-values.yaml
  content/kubernetes-backing-services/ingress/examples/nginx-ingress-usage-helmfile.yaml
  content/kubernetes-backing-services/ingress/examples/nginx-ingress-usage-kubectl-resource.yaml
  content/kubernetes-backing-services/ingress/nginx-ingress-controller.md
  content/secrets-management/aws-kms.md
  content/secrets-management/examples/terraform-apply-aws-kms.text
  content/tools/chamber.md
  layouts/partials/homepage.html
  layouts/shortcodes/include-code-block.html
Labels: documentation

#78 Chamber usage
  .htmltest.yml
  Makefile
  codefresh.yml
  content/development/markdown/_index.md
  content/geodesic/_index.md
  content/geodesic/design.md
  content/glossary/cicd.md
  content/glossary/codefresh.md
  content/glossary/continuous-delivery.md
  content/glossary/continuous-integration.md
  content/glossary/crud.md
  content/glossary/mfa.md
  content/helm-charts/quickstart.md
  content/kubernetes/pull-secrets.md
  content/kubernetes/resource-management.md
  content/release-engineering/build-harness.md
  content/release-engineering/codefresh-kubernetes-integration.md
  content/release-engineering/codefresh.md
  content/secrets-management/_index.md
  content/secrets-management/anti-patterns.md
  content/secrets-management/aws-kms-s3.md
  content/secrets-management/aws-kms-ssm.md
  content/secrets-management/best-practices.md
  content/secrets-management/cicd.md
  content/secrets-management/development.md
  content/secrets-management/examples/chamber-with-codefresh.yaml
  content/secrets-management/examples/encrypted-bucket.tf
  content/secrets-management/examples/terraform-apply-aws-kms.txt
  content/secrets-management/terraform.md
  content/terraform-modules/root/codefresh-pipeline.md
  content/terraform-modules/security/terraform-aws-iam-system-user.md
  content/tools/1password.md
  content/tools/chamber.md
  content/tools/goofys.md
  static/assets/1password-57e89599.png
  static/assets/1password-ca184eb3.png
  static/assets/1password-e3bc9e9c.png
Labels: customer, documentation, enhancement

#89 Document Rollbacks
  content/faq/examples/helm-rollback.txt
  content/faq/how-to-perform-rollbacks.md
  static/assets/how-to-do-rollback-110761f7.png
  static/assets/how-to-do-rollback-534718a5.png
  static/assets/how-to-do-rollback-726fd44e.png
  static/assets/how-to-do-rollback-bb9fc21b.png
  static/assets/how-to-do-rollback-c23f0d87.png
  static/assets/how-to-do-rollback-f30ef835.png
Labels: customer, documentation

#87 Added documentation for portal
  content/kubernetes-platform-services/_index.md
  content/kubernetes-platform-services/artifact-storage/_index.md
  content/kubernetes-platform-services/dashboard/_index.md
  content/kubernetes-platform-services/dashboard/cluster-portal.md
  content/kubernetes-platform-services/dashboard/examples/portal-helmfile-sync.txt
  content/kubernetes-platform-services/dashboard/examples/portal-helmfile.yaml
  content/kubernetes-platform-services/dashboard/examples/values-portal.yaml
  content/kubernetes-platform-services/dashboard/kubernetes-ui-dashboard.md
  static/assets/cluster-portal-9fada4bb.png
Labels: customer, documentation

#95 Document helmfile usage
  content/geodesic/module/with-kops.md
  content/glossary/cli.md
  content/glossary/kubectl.md
  content/kubernetes/kubectl.md
  content/release-engineering/codefresh-kubernetes-integration.md
  content/tools/examples/helmfile-usage.txt
  content/tools/examples/helmfile.yaml
  content/tools/helmfile.md
Labels: customer, documentation, enhancement

#98 Document prometheus & portal configuration
  Makefile
  content/kubernetes-backing-services/external-dns/external-dns.md
  content/kubernetes-backing-services/iam/kube2iam.md
  content/kubernetes-backing-services/ingress/nginx-ingress-controller.md
  content/kubernetes-backing-services/monitoring/examples/kube-prometheus-helmfile.yaml
  content/kubernetes-backing-services/monitoring/examples/prometheus-operator-helmfile.yaml
  content/kubernetes-backing-services/monitoring/kube-prometheus.md
  content/kubernetes-backing-services/monitoring/prometheus-alerts-grafana.md
  content/kubernetes-backing-services/monitoring/prometheus-operator.md
  content/kubernetes-backing-services/tls-management/kube-lego-lets-encrypt.md
  content/kubernetes-optimization/scale-nginx-ingress-horizontally.md
  content/kubernetes-optimization/scale-nginx-ingress-vertically.md
  content/kubernetes-platform-services/dashboard/cluster-portal.md
  content/kubernetes-platform-services/dashboard/examples/example-portal.backends.yaml
  content/monitoring-and-alerting/alert-manager.md
  content/monitoring-and-alerting/grafana.md
  content/monitoring-and-alerting/prometheus.md
  content/secrets-management/aws-kms-ssm.md
  content/terraform-modules/root/codefresh-pipeline.md
  static/assets/kube-prometheus-4f06031c.png
  static/assets/kube-prometheus-ce3e9690.png
  static/assets/kube-prometheus-d0d17131.png
  static/assets/kube-prometheus-f5f4472c.png
Labels: customer, documentation

#96 Document Kops Upgrades
  README.md
  content/geodesic/kops/_index.md
  content/geodesic/kops/manifest.md
  content/geodesic/kops/resize-cluster.md
  content/geodesic/kops/ssh.md
  content/geodesic/kops/update-cluster.md
  content/geodesic/kops/upgrade-cluster.md
  content/glossary/bastion.md
  content/glossary/declarative.md
  content/glossary/imperative.md
  content/glossary/topology.md
  content/tools/gomplate.md
  content/tools/kops.md
  static/assets/gomplate-5869374e.png
Labels: customer, documentation, enhancement, wip
